//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarkWord.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MarkWord.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 /* GitHub stylesheet for MarkdownPad (http://markdownpad.com) */
        ////* Author: Nicolas Hery - http://nicolashery.com */
        ////* Version: b13fe65ca28d2e568c6ed5d7f06581183df8f2ff */
        ////* Source: https://github.com/nicolahery/markdownpad-github */
        ///
        ////* RESET
        ///=============================================================================*/
        ///
        ///html, body, div, span, applet, object, iframe, h1, h2, h3, h4, h5, h6, p, blockquote, pre, a, abbr, acronym, address, big, cite, code, del, dfn, em, img, ins, kbd, q, s, samp, s [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string DefaultStyle {
            get {
                return ResourceManager.GetString("DefaultStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;!--sublog
        ///{
        ///    &quot;title&quot;:&quot;Sublog: 支持Markdown和语法高亮的跨平台博客客户端&quot;,
        ///    &quot;category&quot;:&quot;Thinking&quot;,
        ///    &quot;tags&quot;:&quot;&quot;,
        ///    &quot;publish&quot;:&quot;true&quot;,
        ///    &quot;blog_id&quot;:&quot;3151861&quot;
        ///}
        ///sublog--&gt;
        ///
        ///灵感来自[米米饭](http://www.cnblogs.com/meetrice/archive/2013/02/14/2911238.html)
        ///
        ///## 功能一览
        ///[为什么你应该试试用Sublog写博客](http://www.cnblogs.com/zhengwenwei/p/3175646.html)
        ///
        ///## 项目主页：
        ///[sublog](https://github.com/AmongOthers/sublog)
        ///
        ///
        ///## 使用方法：
        ///
        ///1. 本项目是一个插件，首先要安装[Sublime Text 2](http://www.sublimetext.com/2)
        ///
        ///1. 重命名sublog.sublime-settings.exampl [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string test {
            get {
                return ResourceManager.GetString("test", resourceCulture);
            }
        }
    }
}
